name: bdix_ftps
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  get: 4.6.5
  super_ui_kit:
    git:
      url: https://github.com/krzshipon/super_ui_kit.git
      ref: dev
  water_drop_nav_bar: ^2.2.0+5
  flutter: 
    sdk: flutter
  url_launcher: ^6.1.12

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

